language: python
arch:
  - amd64
  - ppc64le
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install nose coverage coveralls"
  - "pip install --editable ."
script: nosetests dodgy -s --with-coverage --cover-inclusive --cover-package=dodgy
after_success: coveralls
